const config = require('./config')

module.exports = {
  GRID_SIZE: 100,
  FPS: 60,
  GROW_FACTOR: 0.1,
  FOOD_RADIUS: 0.5,
  FOOD_NODE_AMOUNT: 120,
  ITEM_RADIUS: 1,
  ITEM_NODE_AMOUNT: 10,
  ITEM_SPEEDUP_FACTOR: 2,
  OBSTACLE_MIN_RADIUS: 4,
  OBSTACLE_MAX_RADIUS: 6,
  OBSTACLE_MAX_LIFE_TIME: 60000,
  OBSTACLE_MIN_LIFE_TIME: 30000,
  PLAYER_RADIUS: 2,
  PLAYER_SPEED: 5,
  PLAYER_RESET_FACTOR: 0.25,
  DEFAULT_SPEEDUP_FACTOR: 2,
  DEFAULT_GROWUP_FACTOR: 2,
  DEFAULT_USEREVENT_TIME: 1000,
  DEFAULT_ITEM_ACTIVE_TIME: 10000,
  DEFAULT_INVULNERABILITY_TIME: 100,
  DEFAULT_PLAYER_SPRITE: `${config.http}${config.host}:8080/player.png`,
  DEFAULT_FOOD_SPRITE: `${config.http}${config.host}:8080/food.png`,
  DEFAULT_VIRUS_SPRITE: `${config.http}${config.host}:8080/virus.png`,
  DEFAULT_WARP_SPRITE: `${config.http}${config.host}:8080/warp.png`,
  DEFAULT_INVULNERABILITY_SPRITE: `${config.http}${config.host}:8080/invulnerable.png`,
  DEFAULT_ITEM_SPEEDUP_SPRITE: `${config.http}${config.host}:8080/speedUp.png`,
  DEFAULT_ITEM_INVULNERABILITY_SPRITE: `${config.http}${config.host}:8080/itemInvulnerable.png`,
  DEFAULT_ITEM_GROWUP_SPRITE: `${config.http}${config.host}:8080/growUp.png`,
}
